apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mautrix-signal.fullname" . }}-config
  labels:
    {{- include "mautrix-signal.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.mautrixSignalConfig | nindent 4 }}
